services:
  api:
    build:
      context: .
    container_name: mini-data-platform-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mini-data-platform-redis
    restart: unless-stopped

  airflow-db:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-db-data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:3.3.0
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: db migrate

  airflow:
    build:
      context: ./airflow
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      PYTHONPATH: /opt/airflow
      GOOGLE_APPLICATION_CREDENTIALS: /home/airflow/.config/gcloud/application_default_credentials.json
      GOOGLE_CLOUD_PROJECT: mini-data-platform-507211
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ${HOME}/.config/gcloud:/home/airflow/.config/gcloud:ro
    ports:
      - "8080:8080"
    command: standalone

volumes:
  airflow-db-data: