version: 2

models:
  - name: stg_products
    columns:
      - name: product_id
        data_tests:
          - not_null
          - unique

      - name: name
        data_tests:
          - not_null

  - name: stg_users
    columns:
      - name: user_id
        data_tests:
          - not_null
          - unique

      - name: email
        data_tests:
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        data_tests:
          - not_null

      - name: user_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_users')
                field: user_id

      - name: product_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_products')
                field: product_id

      - name: quantity
        data_tests:
          - not_null